features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
slideshow_display: 1
show_social_icons: 1
slide_title_1: Cupcakes!
slide_description_1: 'Tart pie fruitcake macaroon jelly beans marshmallow pie oat cake caramels. Cotton candy macaroon chupa chups candy icing.'
slide_url_1: /article/2018/05/cupcakes
slide_image_path_1: /images/parallax-slider/slide_one.png
slide_title_2: Wafers
slide_head_2: 'Fully Responsive'
slide_description_2: 'Carrot cake marzipan toffee caramels candy I love.'
slide_url_2: /article/2018/05/wafers
slide_image_path_2: /images/parallax-slider/slide_two.png
slide_title_3: Croissant
slide_description_3: 'Gummies chocolate liquorice I love chocolate cake biscuit jelly beans tart cheesecake.'
slide_url_3: /article/2018/05/croissant
slide_image_path_3: /images/parallax-slider/slide_three.png
slide_title_4: Tiramisu
slide_description_4: 'Tiramisu pudding fruitcake.'
slide_url_4: /article/2018/05/tiramisu
slide_image_path_4: /images/parallax-slider/slide-four.png
slide_title_5: Danish
slide_description_5: 'Halvah powder danish icing I love cake donut oat cake lollipop.'
slide_url_5: /article/2018/05/danish-pastry
slide_image_path_5: /images/parallax-slider/slide_five.png
_core:
  default_config_hash: GUen8U73yQwuBi2qK5mVGvpCKzdvos_C0K-VTBt9qlI
logo:
  use_default: 0
  path: 'public://pink_muffin_0.png'
favicon:
  use_default: 1
slide_image_path1:
  - '6'
slide_image_path2:
  - '9'
slide_image_path3:
  - '10'
slide_image_path4:
  - '12'
slide_image_path5:
  - '14'
social_icon_display: 0
facebook_url: ''
google_plus_url: ''
twitter_url: ''
linkedin_url: ''
pinterest_url: ''
rss_url: ''
